import "server-only";
import { eq, sql, type SQL } from "drizzle-orm";
import { db, type Executor } from "@/db";
import { orders, payments, returnItems, returns } from "@/db/schema";
import { writeAudit } from "@/lib/audit";
import type { PaymentMethod } from "@/db/schema";

/**
 * Payments and the outstanding balance (§5.4).
 *
 * The balance is always derived, never stored:
 *
 *   balance = order total − payments received − credit for returned goods
 *
 * Returns belong in that sum because §11 requires a return to correct the
 * customer's debt: goods that came back are not owed for.
 */

export class PaymentError extends Error {
  constructor(
    public reason: "NOT_SHIPPED" | "EXCEEDS_BALANCE" | "NOT_FOUND",
    public balanceCents = 0,
  ) {
    super(`Payment rejected: ${reason}`);
    this.name = "PaymentError";
  }
}

export interface OrderBalance {
  totalCents: number;
  paidCents: number;
  returnedCents: number;
  balanceCents: number;
  fullyPaid: boolean;
}

/**
 * Credit generated by returns against an order. Takes a qualified column
 * reference (see `lib/sql.ts`) or a literal id, never a bare Drizzle column.
 */
export const returnedCentsSql = (orderRef: SQL | string) => sql<number>`COALESCE((
  SELECT SUM(ri.qty_units * ri.unit_price_cents)
    FROM return_items ri
    JOIN returns r ON r.id = ri.return_id
   WHERE r.order_id = ${orderRef}
), 0)`;

export async function getOrderBalance(
  orderId: string,
  exec: Executor = db,
): Promise<OrderBalance | null> {
  const [row] = await exec
    .select({
      totalCents: orders.totalCents,
      paidCents: sql<number>`COALESCE((
        SELECT SUM(p.amount_cents) FROM payments p WHERE p.order_id = ${orderId}
      ), 0)`,
      returnedCents: returnedCentsSql(orderId),
    })
    .from(orders)
    .where(eq(orders.id, orderId));

  if (!row) return null;

  const total = Number(row.totalCents);
  const paid = Number(row.paidCents);
  const returned = Number(row.returnedCents);
  const balance = total - paid - returned;

  return {
    totalCents: total,
    paidCents: paid,
    returnedCents: returned,
    balanceCents: balance,
    // Treat an over-credited order as settled rather than as a negative debt.
    fullyPaid: balance <= 0,
  };
}

export interface RecordPaymentInput {
  orderId: string;
  paidOn: string;
  amountCents: number;
  method: PaymentMethod;
  note: string | null;
}

/**
 * Record a payment, in full or in part (§5.4).
 *
 * Rejects an amount above the outstanding balance: overpayment is almost always
 * a typo, and silently accepting it would put the receivables report into
 * negative numbers that nobody can reconcile.
 */
export async function recordPayment(
  actorId: string,
  input: RecordPaymentInput,
): Promise<void> {
  await db.transaction(async (tx) => {
    const [order] = await tx
      .select({ id: orders.id, number: orders.number, status: orders.status })
      .from(orders)
      .where(eq(orders.id, input.orderId));
    if (!order) throw new PaymentError("NOT_FOUND");

    // §5.4: the credit clock starts at shipment, so payments attach to a
    // shipped order.
    if (order.status !== "SHIPPED") throw new PaymentError("NOT_SHIPPED");

    const balance = await getOrderBalance(input.orderId, tx);
    if (!balance) throw new PaymentError("NOT_FOUND");
    if (input.amountCents > balance.balanceCents) {
      throw new PaymentError("EXCEEDS_BALANCE", balance.balanceCents);
    }

    const [row] = await tx
      .insert(payments)
      .values({
        orderId: input.orderId,
        paidOn: input.paidOn,
        amountCents: input.amountCents,
        method: input.method,
        note: input.note,
        userId: actorId,
      })
      .returning({ id: payments.id });

    await writeAudit(
      {
        userId: actorId,
        entity: "payment",
        entityId: row.id,
        action: "payment",
        label: order.number,
        newValue: {
          amountCents: input.amountCents,
          paidOn: input.paidOn,
          method: input.method,
          balanceBeforeCents: balance.balanceCents,
        },
      },
      tx,
    );
  });
}

/** Remove a mistaken payment. Audited, because it changes a customer's debt. */
export async function deletePayment(actorId: string, paymentId: string): Promise<void> {
  await db.transaction(async (tx) => {
    const [row] = await tx
      .select({
        id: payments.id,
        orderId: payments.orderId,
        amountCents: payments.amountCents,
        paidOn: payments.paidOn,
        number: orders.number,
      })
      .from(payments)
      .innerJoin(orders, eq(orders.id, payments.orderId))
      .where(eq(payments.id, paymentId));
    if (!row) throw new PaymentError("NOT_FOUND");

    await tx.delete(payments).where(eq(payments.id, paymentId));

    await writeAudit(
      {
        userId: actorId,
        entity: "payment",
        entityId: paymentId,
        action: "delete",
        label: row.number,
        oldValue: { amountCents: Number(row.amountCents), paidOn: row.paidOn },
      },
      tx,
    );
  });
}

/** Quantities already returned per order line, so a return cannot exceed shipment. */
export async function getReturnedQuantities(
  orderId: string,
  exec: Executor = db,
): Promise<Map<string, number>> {
  const rows = await exec
    .select({
      orderItemId: returnItems.orderItemId,
      qty: sql<number>`SUM(${returnItems.qtyUnits})`,
    })
    .from(returnItems)
    .innerJoin(returns, eq(returns.id, returnItems.returnId))
    .where(eq(returns.orderId, orderId))
    .groupBy(returnItems.orderItemId);

  const out = new Map<string, number>();
  for (const r of rows) {
    if (r.orderItemId) out.set(r.orderItemId, Number(r.qty));
  }
  return out;
}
