/**
 * Reference data: administrative regions of Uzbekistan and their districts.
 * Seeded once; admin-editable later. District lists cover the main tumanlar/
 * cities per region — extend as needed without a schema change.
 */
export interface RegionSeed {
  code: string;
  name: string;
  districts: string[];
}

export const REGIONS: RegionSeed[] = [
  {
    code: "TSH_CITY",
    name: "Tashkent City",
    districts: [
      "Bektemir",
      "Chilonzor",
      "Mirobod",
      "Mirzo Ulug'bek",
      "Olmazor",
      "Sergeli",
      "Shayxontohur",
      "Uchtepa",
      "Yakkasaroy",
      "Yashnobod",
      "Yunusobod",
      "Yangihayot",
    ],
  },
  {
    code: "TSH_REG",
    name: "Tashkent Region",
    districts: [
      "Bekobod",
      "Bo'ka",
      "Bo'stonliq",
      "Chinoz",
      "Qibray",
      "Ohangaron",
      "Oqqo'rg'on",
      "Parkent",
      "Piskent",
      "Quyichirchiq",
      "O'rtachirchiq",
      "Yangiyo'l",
      "Yuqorichirchiq",
      "Zangiota",
    ],
  },
  {
    code: "AND",
    name: "Andijan",
    districts: [
      "Andijon",
      "Asaka",
      "Baliqchi",
      "Bo'z",
      "Buloqboshi",
      "Izboskan",
      "Jalaquduq",
      "Marhamat",
      "Oltinko'l",
      "Paxtaobod",
      "Qo'rg'ontepa",
      "Shahrixon",
      "Ulug'nor",
      "Xo'jaobod",
    ],
  },
  {
    code: "BUX",
    name: "Bukhara",
    districts: [
      "Buxoro",
      "G'ijduvon",
      "Jondor",
      "Kogon",
      "Olot",
      "Peshku",
      "Qorako'l",
      "Qorovulbozor",
      "Romitan",
      "Shofirkon",
      "Vobkent",
    ],
  },
  {
    code: "FAR",
    name: "Fergana",
    districts: [
      "Farg'ona",
      "Bag'dod",
      "Beshariq",
      "Buvayda",
      "Dang'ara",
      "Furqat",
      "Qo'shtepa",
      "Quva",
      "Rishton",
      "So'x",
      "Toshloq",
      "Uchko'prik",
      "O'zbekiston",
      "Yozyovon",
    ],
  },
  {
    code: "JIZ",
    name: "Jizzakh",
    districts: [
      "Jizzax",
      "Arnasoy",
      "Baxmal",
      "Do'stlik",
      "Forish",
      "G'allaorol",
      "Mirzacho'l",
      "Paxtakor",
      "Yangiobod",
      "Zarbdor",
      "Zafarobod",
      "Zomin",
    ],
  },
  {
    code: "XOR",
    name: "Khorezm",
    districts: [
      "Urganch",
      "Bog'ot",
      "Gurlan",
      "Hazorasp",
      "Xiva",
      "Qo'shko'pir",
      "Shovot",
      "Xonqa",
      "Yangiariq",
      "Yangibozor",
    ],
  },
  {
    code: "NAM",
    name: "Namangan",
    districts: [
      "Namangan",
      "Chortoq",
      "Chust",
      "Kosonsoy",
      "Mingbuloq",
      "Norin",
      "Pop",
      "To'raqo'rg'on",
      "Uchqo'rg'on",
      "Uychi",
      "Yangiqo'rg'on",
    ],
  },
  {
    code: "NAV",
    name: "Navoi",
    districts: [
      "Navoiy",
      "Konimex",
      "Karmana",
      "Qiziltepa",
      "Xatirchi",
      "Nurota",
      "Tomdi",
      "Uchquduq",
      "Zarafshon",
    ],
  },
  {
    code: "QASH",
    name: "Kashkadarya",
    districts: [
      "Qarshi",
      "Chiroqchi",
      "Dehqonobod",
      "G'uzor",
      "Kasbi",
      "Kitob",
      "Koson",
      "Mirishkor",
      "Muborak",
      "Nishon",
      "Qamashi",
      "Shahrisabz",
      "Yakkabog'",
    ],
  },
  {
    code: "QORA",
    name: "Karakalpakstan",
    districts: [
      "Nukus",
      "Amudaryo",
      "Beruniy",
      "Chimboy",
      "Ellikqal'a",
      "Kegeyli",
      "Mo'ynoq",
      "Nukus tumani",
      "Qanliko'l",
      "Qo'ng'irot",
      "Qorao'zak",
      "Shumanay",
      "Taxiatosh",
      "To'rtko'l",
      "Xo'jayli",
    ],
  },
  {
    code: "SAM",
    name: "Samarkand",
    districts: [
      "Samarqand",
      "Bulung'ur",
      "Ishtixon",
      "Jomboy",
      "Kattaqo'rg'on",
      "Narpay",
      "Nurobod",
      "Oqdaryo",
      "Pastdarg'om",
      "Paxtachi",
      "Payariq",
      "Qo'shrabot",
      "Toyloq",
      "Urgut",
    ],
  },
  {
    code: "SIR",
    name: "Syrdarya",
    districts: [
      "Guliston",
      "Boyovut",
      "Mirzaobod",
      "Oqoltin",
      "Sardoba",
      "Sayxunobod",
      "Sirdaryo",
      "Xovos",
      "Yangiyer",
    ],
  },
  {
    code: "SUR",
    name: "Surkhandarya",
    districts: [
      "Termiz",
      "Angor",
      "Bandixon",
      "Boysun",
      "Denov",
      "Jarqo'rg'on",
      "Muzrabot",
      "Oltinsoy",
      "Qiziriq",
      "Qumqo'rg'on",
      "Sariosiyo",
      "Sherobod",
      "Sho'rchi",
      "Uzun",
    ],
  },
];
